export const ASESORES_PISO = [
    "Adrian Galvez Roldan",
    "Aura Marlizeth Fernandez Lopez",
    "Bianca Isabel Chavez Alarcon",
    "Blanca Patricia Hernandez Hernandez",
    "Candy Denisse Marquez Cortes",
    "Carlos Arturo Garces Vengas",
    "Cesar Ivan Salazar Reyes",
    "Cristian Fernando Rivera Godinez",
    "David Uriel García Navarro",
    "Delmar Javier Illescas Dominguez",
    "Dulce Abigail Garcia Olivares",
    "Edgar Jesus Gomez Perez",
    "Edgar Omar Noguera Solis",
    "Elia Ines Arano Reyes",
    "Erendira Santos Coyotzi",
    "Estefano Marlom De Azcue Aparicio",
    "Felix Emmanuel Solis Angeles",
    "Geovani Nava Diaz",
    "German Jarith Salazar Miranda",
    "Gustavo Chontal Romero",
    "Hector Rodriguez",
    "Idalmy Jimenez Sanchez",
    "Irene Del Carmen Guiza Lopez",
    "Iris Yazmín Gómez Velázquez",
    "Israel Garcia Juarez",
    "Ivan Juarez Ortega",
    "Javier Perez Meraz",
    "Jessica Olivares Campos",
    "Jesus Xitlama Gomez",
    "Jorge Antonio Rodriguez Martinez",
    "Jorge Luis Alamillo Rodriguez",
    "Jose Alberto Sedas Flores",
    "Jose Alfredo Barranca Reyes",
    "Jose De Jesus Garcia Roman",
    "Juan Jesus Marquez Aquino",
    "Juan Manuel Sobrevilla Vicencio",
    "Julio Ramirez Lopez",
    "Lizbeth Cano Clara",
    "Luis Alberto Ramirez Santamaria",
    "Luis Alfonso Coria Marroquin",
    "Luis Armando Almora Perez",
    "Luis Manuel Alvarez Martinez",
    "Luis Manuel Hernández Espejo",
    "Luis Manuel Palomares Olayo",
    "Mara Erubey Soto Villegas",
    "Marcos Raul Diaz Ramos",
    "Marelly Tenorio Salinas",
    "Maria De Guadalupe Vanvollenhoven Diaz",
    "Maria Del Carmen Zavala Velazquez",
    "Maria Monserrath Zarate Gamboa",
    "Mario Alberto Lopez Ramos",
    "Marisol Lagunes Gonzalez",
    "Miguel Capitanachi Paredes",
    "Nallely Hernandez Garcia",
    "Octavio Bruno Gonzalez",
    "Olimpia Vazquez Mendez",
    "Omar Villiers Mondragon",
    "Paul Serrano Vera",
    "Roberto Ramses Luna Fajardo",
    "Rogelio Vazquez Sanchez",
    "Ruben Alberto Tosquy Adriano",
    "Ruben Romero Valdes",
    "Saja Azzam Mohammad Jamous",
    "Sandra Luz Prieto Perez",
    "Sergio Ivan Quintana Martinez",
    "Sergio Rene Delgado Sarmiento",
    "Valeria Zilli Durante",
    "Vanessa Jimenez Medina",
    "Veronica Castillo Fuentes",
    "Yamil Misael Rodriguez Aguilar",
    "Yoseth Ruiz Castellanos",
    "Zeila Navarro Contreras",
];

export const AGENCIAS_DIGITALES = [
    "VW Cordoba",
    "VW Cordoba-Usados",
    "VW Orizaba",
    "VW Orizaba-Usados",
    "VW Poza Rica",
    "VW Tuxtepec",
    "VW Tuxpan",
    "Automotriz R&R",
];
