export const PUESTOS = [
    { id: 1, nombre: "Asesor de ventas nuevos", categoria: "Ventas", dependeDe: "Gerente de Ventas" },
    { id: 2, nombre: "Asesor de ventas seminuevos", categoria: "Ventas", dependeDe: "Gerente de Ventas" },
    { id: 3, nombre: "Asistente de ventas", categoria: "Ventas", dependeDe: "Gerente de Ventas" },
    { id: 4, nombre: "Servicios Financieros", categoria: "Ventas", dependeDe: "Gerente de Ventas" },
    { id: 5, nombre: "Coordinador de AFASA", categoria: "Ventas", dependeDe: "Gerente de Ventas" },
    { id: 6, nombre: "Preparador", categoria: "Postventa", dependeDe: "Gerente de Postventa" },
    { id: 7, nombre: "Lavador", categoria: "Operaciones", dependeDe: "Jefe de Taller" },
    { id: 8, nombre: "Cajera", categoria: "Administración", dependeDe: "Gerente General" },
    { id: 9, nombre: "Auxiliar contable", categoria: "Administración", dependeDe: "Contador General" },
    { id: 10, nombre: "Contador General", categoria: "Administración", dependeDe: "Gerente General" },
    { id: 11, nombre: "Gerente de ventas", categoria: "Ventas", dependeDe: "Gerente General" },
    { id: 12, nombre: "Gerente de Servicio", categoria: "Servicio", dependeDe: "Gerente General" },
    { id: 13, nombre: "Gerente de refacciones", categoria: "Refacciones", dependeDe: "Gerente General" },
    { id: 14, nombre: "Gerente de postventa", categoria: "Postventa", dependeDe: "Gerente General" },
    { id: 15, nombre: "Gerente de HYP", categoria: "HYP", dependeDe: "Gerente General" },
    { id: 16, nombre: "Asesor de HYP", categoria: "HYP", dependeDe: "Gerente de HYP" },
    { id: 17, nombre: "Técnico Hojalatero", categoria: "Postventa", dependeDe: "Gerente de Postventa" },
    { id: 18, nombre: "Técnico pintor", categoria: "Postventa", dependeDe: "Gerente de Postventa" },
    { id: 19, nombre: "Técnico mecanico", categoria: "Servicio", dependeDe: "Jefe de Taller" },
    { id: 20, nombre: "Asesor de servicio", categoria: "Servicio", dependeDe: "Gerente de Servicio" },
    { id: 21, nombre: "Asistente de servicio", categoria: "Servicio", dependeDe: "Gerente de Servicio" },
    { id: 22, nombre: "Administrador de garantía", categoria: "Servicio", dependeDe: "Gerente de Servicio" },
    { id: 23, nombre: "Jefe de taller", categoria: "Servicio", dependeDe: "Gerente de Servicio" },
    { id: 24, nombre: "Técnico Master", categoria: "Servicio", dependeDe: "Gerente de Servicio" },
    { id: 25, nombre: "Asesor de refacciones mostrador taller", categoria: "Refacciones", dependeDe: "Gerente de Refacciones" },
    { id: 26, nombre: "Asesor de refacciones mostrador publico", categoria: "Refacciones", dependeDe: "Gerente de Refacciones" },
    { id: 27, nombre: "Asesor de refacciones promotoria NORA", categoria: "Refacciones", dependeDe: "Gerente de Refacciones" },
    { id: 28, nombre: "Encargado de almacen", categoria: "Refacciones", dependeDe: "Gerente de Refacciones" },
    { id: 29, nombre: "Asesor de ventas digitales", categoria: "Ventas", dependeDe: "Gerente de Ventas" },
    { id: 30, nombre: "Coordinador de ventas digitales", categoria: "Ventas", dependeDe: "Gerente de Ventas" },
    { id: 31, nombre: "Auditor interno", categoria: "Administración", dependeDe: "Gerente General" },
    { id: 32, nombre: "Contador Fiscal", categoria: "Administración", dependeDe: "Contador General" },
    { id: 33, nombre: "Gerente General", categoria: "Administración", dependeDe: "Dirección" },
    { id: 34, nombre: "Gerente de marketing", categoria: "Marketing", dependeDe: "Gerente General" },
    { id: 35, nombre: "Consultor de procesos", categoria: "Marketing", dependeDe: "Gerente de Marketing" },
    { id: 36, nombre: "Coordinador de marketing", categoria: "Marketing", dependeDe: "Gerente de Marketing" },
    { id: 37, nombre: "Hostess", categoria: "Operaciones", dependeDe: "Gerente General" },
    { id: 38, nombre: "Contact Center", categoria: "Operaciones", dependeDe: "Gerente de Ventas" },
    { id: 39, nombre: "Trasladista", categoria: "Operaciones", dependeDe: "Gerente de Servicio" },
    { id: 40, nombre: "Valuador de seminuevos", categoria: "Ventas", dependeDe: "Gerente de Ventas" },
    { id: 41, nombre: "Control de calidad", categoria: "Calidad", dependeDe: "Gerente de Calidad" },
    { id: 42, nombre: "Afanador", categoria: "Operaciones", dependeDe: "Gerente General" },
    { id: 43, nombre: "Vigilancia", categoria: "Operaciones", dependeDe: "Gerente General" },
    { id: 44, nombre: "Oficial de cumplimiento", categoria: "Administración", dependeDe: "Gerente General" },
    { id: 45, nombre: "Especialista de entregas", categoria: "Ventas", dependeDe: "Gerente de Ventas" },
    { id: 46, nombre: "Desarrollo organizacional", categoria: "Recursos Humanos", dependeDe: "Gerente General" },
    { id: 47, nombre: "Gerente de calidad", categoria: "Calidad", dependeDe: "Gerente General" },
    { id: 48, nombre: "Gerente de postventa grupo", categoria: "Postventa", dependeDe: "Dirección" },
    { id: 49, nombre: "Credito y cobranza divisional", categoria: "Finanzas", dependeDe: "Dirección" },
    { id: 50, nombre: "Sistemas", categoria: "Sistemas", dependeDe: "Gerente General" },
    { id: 51, nombre: "Contador General de fondos y valores", categoria: "Administración", dependeDe: "Contador General" },
    { id: 52, nombre: "Desarrollo organizacional grupo", categoria: "Recursos Humanos", dependeDe: "Dirección" },
    { id: 53, nombre: "Recursos humanos divisional", categoria: "Recursos Humanos", dependeDe: "Dirección" },
    { id: 54, nombre: "Analista de datos y programación", categoria: "Sistemas", dependeDe: "Sistemas" },
    { id: 55, nombre: "Auxiliar de diseño y producción", categoria: "Marketing", dependeDe: "Coordinador de Marketing" },
];

export const CATEGORIAS = [
    "Todos",
    "Ventas",
    "Servicio",
    "Refacciones",
    "Postventa",
    "HYP",
    "Administración",
    "Operaciones",
    "Marketing",
    "Calidad",
    "Sistemas",
    "Recursos Humanos",
    "Finanzas"
];